#!/bin/bash
rpmpath=$1
if [[ "$rpmpath" =~ ^http.* ]]; then
	pkgname=(${rpmpath//\// })
	pkgname=${pkgname[-1]}
	pkgname=$(echo "$pkgname" | sed "s/.rpm//")
else
	pkgname=$(echo "$rpmpath" | sed "s/.rpm//")
fi
if [ -z $pkgname ]; then
        echo "Failed parse pkg name!"
	exit 4
fi
echo "Making package for '$pkgname'..."
if [ -d $pkgname ]; then
        rm -rf $pkgname
fi
mkdir $pkgname
cd $pkgname
if [[ "$rpmpath" =~ ^http.* ]]; then
	wget -O "$pkgname.rpm" "$rpmpath"
	if [ $? -ne 0 ]; then
		echo "Failed download file!"
		exit 5
	fi
else
	mv "../$pkgname.rpm" "$pkgname.rpm" &> /dev/null
fi
if [ ! -f "$pkgname.rpm" ]; then
	echo "File '$rpmpath' not found!"
	exit 1
fi
cleanpkg=$(echo $pkgname | egrep -o '^[a-z0-9\-]{3,}.' | head -n1)
cleanpkg=${cleanpkg::-3}
if [ -z $cleanpkg ]; then
	echo "Failed parse pkg name!"
	exit 2
else
	echo "Pkg name = $cleanpkg"
fi
version=${pkgname/"$cleanpkg"/}
version=$(echo $version | egrep -o '[[:digit:]\.]{1,}' | head -n1)
if [ -z $version ]; then
        echo "Failed parse pkg version!"
        exit 3
else
        echo "Pkg version = $version"
fi

PKGBUILD="pkgname=\"$cleanpkg\"\npkgver=\"$version\"\npkgrel=\"1\"\npkgdesc=\"$pkgname\"\narch=(\"x86_64\")\nsource=(\"$rpmpath\")\nsha256sums=(\"SKIP\")\n\npackage() {\n\tfind \$srcdir/ -mindepth 1 -maxdepth 1 -type d | xargs cp -r -t \"\$pkgdir\"\n}"

echo -e $PKGBUILD | tee PKGBUILD &> /dev/null
echo "Build and install package..."
sudo makepkg -si
exit 0
